### ISSUE TITLE
fs.rmdirSync() doesn't delete non-empty directories

### ISSUE THREAD

**Issue by alexjlockwood** [romannurik/Sketch-FlowExporter#11]
Hello there... I'm back on your GitHub trying to learn how to write sketch plugins... this repo has been the most useful (I'm trying to write a Sketch-to-VectorDrawable plugin).

Anyway... I have been reading your code and I noticed that there is a call to `fs.rmdirSync()` that doesn't seem to handle the case where the deleted directory is non-empty:

https://github.com/romannurik/Sketch-FlowExporter/blob/master/src/command-export-html.js#L114

Just wondering if that was intentional...

**Comment by romannurik** [comment]
Hey hey! Not sure I follow. Do you mean handling the case where it *is* empty?

**Comment by alexjlockwood** [comment]
`fs.rmdirSync()` has no effect if the directory is non-empty, right (same behavior as the `rmdir` bash command)?

Do you want your code to delete the directory in both cases (whether it is empty or non-empty)? Or only the case where the directory is empty?

**Comment by romannurik** [comment]
Oh dur. Yes. Seems like a bug :-)

**Comment by alexjlockwood** [comment]
Annoyingly I couldn't figure out the fix... I mean, there are 3rd party libraries that claim to do it, but I feel like this is something that should be easy to achieve using the standard node fs libraries... then again, I know next to nothing about node. -.-

**Comment by romannurik** [comment]
The fix will be to just use NSFileManager directly:

NSFileManager.defaultManager().removeItemAtPath_error_(path, null)
