### ISSUE TITLE
How to set a specific page as the first page?

### ISSUE THREAD

**Issue by DengChunhong** [romannurik/Sketch-FlowExporter#13]
Hello,
I am really appreciate this plugin, and it is easy to use. But I don's know how to select a specific page as the first page?
For example, I am designing a website, which includes a login page and a home page. I exported the artboards from Sketch with Sketch-FlowExporter,and then, I opened the index file with browser. The website started from home page, not login page, which was not I expected.

**Comment by romannurik** [comment]
Hi there, I think there's a menu option under the Prototyping menu, when you have an artboard selected, to mark it as a starting point (in Sketch you can mark multiple starting points but the exporter currently just chooses one)
