### ISSUE TITLE
Scroll bars when viewing prototype in browser

### ISSUE THREAD

**Issue by jtomeck** [romannurik/Sketch-FlowExporter#14]
`.prototype-container` should have `overflow:hidden;` instead of `overflow:scroll;`

**Comment by romannurik** [comment]
This is intentional, as sometimes you have longer pages that don't all fit on-screen. `overflow:auto` may be a safer bet. Is there a specific reason you want to avoid scrollbars?

**Comment by JMCAcademy** [comment]
Im am getting the prototype and scroll bars in the middle of the browser even when the browser window has enough space.

**Comment by jtomeck** [comment]
@romannurik All my prototypes, regardless of height, shrink proportionately to the height of the screen when I resize. If that is the intended behavior, scrollbars are not needed. The scroll bars also cover up a few pixels on the right and bottom parts of the prototype. I personally preferred when they remained actual size and needed to scroll in the browser window.

**Comment by romannurik** [comment]
I'm considering simply hiding the scrollbars altogether BTW. Still allowing scrolling but just hiding the bars.

**Comment by josephbergdoll** [comment]
No scrolling + the weird zoom scaling is a huge bummer. It'd be great if this just exported the same thing as sketch cloud.

**Comment by JMCAcademy** [comment]
@romannurik this is still a bug, any chance this will be fixed?

**Comment by romannurik** [comment]
I just pushed v0.2.1, which hides scrollbars on webkit browsers and has more consistent scrolling handling w/ Sketch.

**Comment by jtomeck** [comment]
Thanks @romannurik, I'm lovin' it.
