### ISSUE TITLE
[macOS Sierra] Set Prototype Export Options does nothing 

### ISSUE THREAD

**Issue by JMCAcademy** [romannurik/Sketch-FlowExporter#15]
The options dialogue does not appear when "Set Prototype Export Options" is selected from the menu. 
Sketch version 50.2 (latest).

**Comment by JMCAcademy** [comment]
@romannurik Hi, thanks for the great plug-in. I'm running Sierra 10.12.6 (16G1314) my colleague is on High Sierra who does not get this bug.

 I also have the scroll bar bug.

**Comment by romannurik** [comment]
Ah that's likely the problem... I think the plugin only works on High Sierra. Will need to do some more testing.

**Comment by romannurik** [comment]
This is likely the same as #9 (since prototype options is a Nib-based UI).
