### ISSUE TITLE
How to export a specific page in a multi-page Sketch project?

### ISSUE THREAD

**Issue by alexjlockwood** [romannurik/Sketch-FlowExporter#20]
Sorry if I'm missing something here, but I couldn't figure out how to export a specific page in a multi-page project. 

For example, if I have a project with 5 pages and I want to export the 5th page, it seems like the only way to do that is by temporarily moving the 5th page into the 1st position (so that the exporter will find it first)?

Just wondering if there was an easier way to do this.

**Comment by romannurik** [comment]
The idea for the tool is to export entire flows, most of which have a single starting point. If you wire up your artboards with prototyping connections, the plugin will export every linked-to artboard starting with the one marked as the starting point.

**Comment by alexjlockwood** [comment]
Ahh, OK. Thanks for explaining! I guess I need to learn this prototyping stuff now.

Gonna use your tool to export Shape Shifter mocks to some peeps who are interested in contributing some Firebase-related features. :D

**Comment by romannurik** [comment]
Ah OK! If you need to export static images the simplest is to just export to PNG or such. This plugin is great for exporting basic click-through prototypes Sketch can make.
