### ISSUE TITLE
[macOS High Sierra] There was no reaction at macOS High Sierra

### ISSUE THREAD

**Issue by zaneven** [romannurik/Sketch-FlowExporter#21]
sketch 51
macOS High Sierra 13.4
There was no response after running the command

**Comment by romannurik** [comment]
Hi there! Could you share your Sketch logs right after running this command? Just open the `Console` macOS app, and do a search for Sketch. Then run Sketch and run the command, and try to export/copy/paste as much relevant info as you can here. Thank you!
