### ISSUE TITLE
Hotspots from bottom-fixed elements do not work

### ISSUE THREAD

**Issue by nvasconcelos** [romannurik/Sketch-FlowExporter#22]
Hi Roman, how are you?

When you add a link to an element that's fixed on the screen, it doesn't work :( 

Thanks for this awesome plugin! 

[bug_scroll.zip](https://github.com/romannurik/Sketch-FlowExporter/files/2411994/bug_scroll.zip)

**Comment by romannurik** [comment]
Interesting, looks like when the element itself is fixed and clickable, the plugin breaks, but when the *parent* of a clickable element is fixed to the bottom it works OK. Will invetigate what's causing this, thanks!

**Comment by nvasconcelos** [comment]
Oh, that's a great discovery! 
I was manually fixing my prototyping by finding the bottom fixed hotspots and fixing their CSS (currently, they are getting top fixed instead of bottom fixed)

**Comment by romannurik** [comment]
This will be fully fixed in the next published version
