### ISSUE TITLE
Flow Exporter not working in Sketch 53

### ISSUE THREAD

**Issue by Bertman74** [romannurik/Sketch-FlowExporter#25]
When you try to export your Sketch prototype from Sketch 53+ it only exports the first page of the prototype and does not attempt to create the index.html or any links.  I have tried changing names of the artboards, the export parameters for the artboards and even breaking the links into hotspots, but nothing seems to fix this issue.  We love using this Plugin, but for now have to switch to using "Exporter" which is not as good.
Please fix this ASAP.
Thanks
Mark Bertinetti

**Comment by romannurik** [comment]
Working on it!

**Comment by romannurik** [comment]
Should be fixed in v0.2.2

**Comment by Bertman74** [comment]
I have just installed v0.2.2 and it is still only exporting the first page of my Sketch v53.1 prototype.  it is also not generating the index.html file.  I don't know if this would impact it, but we are using Abstract to manage our Sketch files, but the Plugin seemed to stop working before we started using Abstract.
We really appreciate your help in trying to resolve this issue.
Thanks

**Comment by romannurik** [comment]
Hm, weird. If you can capture Console app output (filter by the word "Sketch") and send it my way, that would help. Alternatively if you could share the example .sketch file you're working with, that would be great as an alternative!

**Comment by Bertman74** [comment]
Hi Nurik,

It must be something with my file.
My colleague using Sketch 53 is delighted as it is working for him now.

Let me have a play and see if I can get to the bottom of it.

Thanks
mark

**Comment by Bertman74** [comment]
Hi Roman,

I have been playing around with it and found the failure is being caused by just 1 symbol I have in my file.
If I delete the 3 instances (one of each on 3 separate artboards) then the prototype exports and works no problem.

It is quite a complex symbol with many repeating symbols within symbols in it.
I am just wondering if there are any layer naming issues that might be the cause ie

  1.  Same names within the symbol
  2.  Too many symbols within symbols
  3.  Layers where the name includes “/”, “*” or other characters?

If you possibly know what I should look for within the symbol, then I will try and fix it and see if it works.
All other symbols (that also have symbols within symbols) see to work fine so it is a bit of a mystery.

Thanks
Mark B

**Comment by romannurik** [comment]
Most likely it's something trying to do with deep meeting, but that's definitely not something that should break the plugin ideally. If you could send me an excerpt sketch file that has that symbol and is breaking, I'd love to fix this :-) you can privately email me: roman at nurik dot net

**Comment by Suru83** [comment]
Hi, I'm using Sketch V 61, is there a fix to this plugin? on exporting 60 % of the UI is not rendered.. CTAs seem to be working in blind spots but still not selectively rendering most components of the screen.

**Comment by romannurik** [comment]
@Suru83 if you can share an example .sketch file with me privately or here publicly I can look into it.

**Comment by Suru83** [comment]
> @Suru83 if you can share an example .sketch file with me privately or here publicly I can look into it.

@romannurik  how do I share it privately ? I think its going to take time to get a reply due to timezones
.. let me share the file here, please do delete it as soon as you download it. thanks!
[kw theming.zip](https://github.com/romannurik/Sketch-FlowExporter/files/3954165/kw.theming.zip)

**Comment by Bertman74** [comment]
Hi there,

Not sure what this is about – Flow exporter seems Ok for now.

Thanks
Mark

**Comment by Suru83** [comment]
@romannurik I cleared the browser cache, but does not seem to work. Only thing I've done before trying this is update Mac to Catalina.. is that a problem :(

**Comment by Suru83** [comment]
@romannurik this is what my screen looks like every time!
<img width="1328" alt="Screenshot 2019-12-12 at 5 02 01 PM" src="https://user-images.githubusercontent.com/17088158/70708733-333c8b00-1d01-11ea-9b95-e8a3ca7f2426.png">
