### ISSUE TITLE
Add an option for resizing browser window to prototype size on load, or center prototype on dark background.

### ISSUE THREAD

**Issue by ozgurgunes** [romannurik/Sketch-FlowExporter#3]
Thanks for this awesome plugin which helps us to stay away from Sketch Cloud. But left aligned prototypes look awful in browser window.

**Comment by romannurik** [comment]
Yeah, this is something that should definitely be added. I'm thinking there would be some in-page options you could open up in the exported file, as opposed to an option during export. Any thoughts on that?

**Comment by ozgurgunes** [comment]
Maybe, but sometimes clients get confused and think that prototype controls are part of the design :)

**Comment by romannurik** [comment]
Oh, I'd imagine they'd be hidden by default to avoid confusion. Designers could press a special key to show the options. (I'm hoping to avoid extra steps during export for now)

**Comment by jeremiahadkins** [comment]
Would love the ability to center the prototype, change bg color and export @2x. Other than that, this plugin is perfect. Thanks again!

**Comment by romannurik** [comment]
Am planning some preferences set at the document or global level, will add 2x and *some* form of viewport customization (not sure exactly how much yet)

**Comment by romannurik** [comment]
FYI, artboards are now centered (and zoomed to fit). The background is still white though... can add an option to change it if that request gains popularity.
