### ISSUE TITLE
The plugin no longer seems to work with Sketch 60.x

### ISSUE THREAD

**Issue by steve-brown-mp** [romannurik/Sketch-FlowExporter#33]
"Export Prototype to HTML" seems to cause no action. No finder dialog opens to save the HTML output.

**Comment by romannurik** [comment]
Will take a look when I'm back in the office!

**Comment by ahusset** [comment]
I confirm nothing happens :(

**Comment by romannurik** [comment]
Hi there, I'm unable to reproduce this with Sketch 61 running on macOS Mojave 10.14.6. Which macOS version are y'all on?

**Comment by steve-brown-mp** [comment]
I'm on Catalina 10.15.1 using Sketch 61

**Comment by romannurik** [comment]
Ah this must be a Catalina thing. I'm not on Catalina so can't test
unfortunately. If anyone can send me error logs that'd be super useful!

**Comment by steve-brown-mp** [comment]
@romannurik What should the behavior be after launching the plugin? The workflow I'm using is to create some links between layers on different artboards, then select Plugins > Flow Export > Export Prototype to HTML. Nothing happens at that point.

Let me know what log to send. Happy to do it. Plugin Log.log?

**Comment by steve-brown-mp** [comment]
This might be it...
Error: An Obj-C exception occurred.
    at [native code] (/)
    at saveDialog (/Users/steve/Library/Application Support/com.bohemiancoding.sketch3/Plugins/FlowExporter.sketchplugin/Contents/Sketch/command-export-html.js:555:40)
    at /Users/steve/Library/Application Support/com.bohemiancoding.sketch3/Plugins/FlowExporter.sketchplugin/Contents/Sketch/command-export-html.js:1780:39
    at __skpm_run (/Users/steve/Library/Application Support/com.bohemiancoding.sketch3/Plugins/FlowExporter.sketchplugin/Contents/Sketch/command-export-html.js:2434:17)
    at __skpm_run[native code] (/)
  nativeException: [<NSSavePanel 0x7fed1493b980> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _cancelButton.

**Comment by romannurik** [comment]
Fixed!

**Comment by romannurik** [comment]
Having trouble publishing due to Apple notarization issues. Will publish the update ASAP

**Comment by steve-brown-mp** [comment]
Thanks @romannurik 
Confirming the plugin works on Catalina with Sketch 61.
It's a nice implementation.

**Comment by romannurik** [comment]
Thanks Steve!
