### ISSUE TITLE
No HTML and .json file since update to Sketch Version 65.1

### ISSUE THREAD

**Issue by CurieGherkin** [romannurik/Sketch-FlowExporter#38]
I use Sketch Version 65.1, after the update the flow export folder contains only the png-files, nothing else. Can you check and help? Thanks!

**Comment by romannurik** [comment]
Arg! Will take a look, thank you for filing.

**Comment by romannurik** [comment]
Hi there! I just tried exporting Sketch's built-in Prototyping Tutorial and it worked OK. Can you share the .sketch file you're trying to export, either here in GitHub or privately via email, so I can see what's causing the error?

**Comment by CurieGherkin** [comment]
I sent you an email, did you receive it?

**Comment by romannurik** [comment]
Hey there! Please try this w/ the new v0.2.7 update
