### ISSUE TITLE
Export starts on random artboard

### ISSUE THREAD

**Issue by nadjaschall** [romannurik/Sketch-FlowExporter#39]
Hi, 

I am experiencing the behavior, that the plugin export starts with a "random" chosen artboard, not with the artboard that is the on top of the sketch layer list, neither with the one sorted by alphabet. Is this a bug or just a not defined behavior within your plugin?

**Comment by romannurik** [comment]
Are any artboards marked as the starting point? The plugin uses that as the
starting point, or IIRC whichever artboard is currently selected?

**Comment by nadjaschall** [comment]
Hi,
now it works, thanks for that. We are used to mark all artboards that should be exported from a different plugin.
