### ISSUE TITLE
How to select an artboard?

### ISSUE THREAD

**Issue by saoirse-zee** [romannurik/Sketch-FlowExporter#4]
First of all, this is a great plugin. Very helpful. I have a couple of (probably dumb) questions:

How do you select a different artboard in the exported prototype site? I only see one of my prototype flows.

How do you specify which artboard to export?

**Comment by romannurik** [comment]
Hey there, I should probably document this but you need to choose an artboard as your starting point before exporting for it to be a useful export. To set it, go into Preview for your prototype and click the flag icon for the artboard you want as your default.
