### ISSUE TITLE
Plugin does not work with Sketch 69 and newer

### ISSUE THREAD

**Issue by nadjaschall** [romannurik/Sketch-FlowExporter#43]
Since Sketch 69 update the plugin does not work anymore. It does not start exporting the artboards.

**Comment by romannurik** [comment]
Can you share a test file that's broken? It's almost certainly related to features within the Sketch file, and not generally broken for all files (I just tested with the built-in Prototyping Tutorial in Sketch and it does work)

**Comment by nadjaschall** [comment]
No unfortunately not, since it contains confidential data. But I have tried with several files, also created a new one. The export starts but then stops again and doesnt finish. 
<img width="324" alt="Bildschirmfoto 2020-10-30 um 14 04 15" src="https://user-images.githubusercontent.com/67323860/97708363-fb753800-1ab8-11eb-9111-a3ee7fbf5017.png">

**Comment by romannurik** [comment]
Hm, that looks like a different plugin... which plugin are you using?
