### ISSUE TITLE
Exporting prototypes fail due to error when trying to analyze/flatten symbols

### ISSUE THREAD

**Issue by janwaechter** [romannurik/Sketch-FlowExporter#54]
Sorry, for adding another one… 😅 

**Description**
As of Sketch 80+ the export fails, due to some error in the [/command-export-html.js](https://github.com/romannurik/Sketch-FlowExporter/blob/d674080acc43c4126f09e9237d17f766fda3db36/src/command-export-html.js). It seems like the plugin has some trouble analyzing the Sketch document.

**Outcome**
- The export fails and no error or success message is displayed within Sketch.
- The export destination (folder) only contains an image of the first screen. Indicating that the export failed already on the first screen/artboard.
- Within the Sketch document, the element that lead to the failure of the export (e.g. an navigation header symbol), has been duplicated and detached from the original symbol.

**Screenshots**
Below I've added two screen grabs from the Sketch DevTools console:
![image](https://user-images.githubusercontent.com/628665/155966841-f2658525-6345-4f0b-ad75-d150c485b778.png)
![image](https://user-images.githubusercontent.com/628665/155966881-0490aec6-487e-416e-8266-c55b28a76eb7.png)

**Comment by romannurik** [comment]
Fixed in v0.2.9 (commit 3ad002dcf1c69b1cd9bded7f4923335f6e57694f)
