### ISSUE TITLE
FlowExporter does not work with Sketch 92 and later anymore

### ISSUE THREAD

**Issue by Tafkadasoh** [romannurik/Sketch-FlowExporter#56]
Hello Roman,

unfortunately, your great plugin gets stuck somewhere and does no export anything anymore when using it with Sketch version 92 or later. 

Could you may be have a look and provide a fix for that issue?

Best regards
Martin

**Comment by romannurik** [comment]
Hi there thanks for reporting! Finally got around to this... fixing now

**Comment by romannurik** [comment]
Should be fixed in 0.2.10, though it's very possible this is going to degrade over time as Sketch grows and my team stops using it :-/

**Comment by Tafkadasoh** [comment]
Hi,
thanks a lot for fixing this issue in 0.2.10! I understand that it does not make sense for you to continue development, so I'm very glad that you've still fixed the issue! We still use your plugin for documenting click-prototypes in our specifications independently from Sketch Cloud. So big appreciation from my side for your plugin and the fix!

Best regards
Martin

**Comment by romannurik** [comment]
I appreciate it and am glad it's helping you! So long as the fixes are really easy this is sustainable :)
