### ISSUE TITLE
Converts shape layers to combined shapes.

### ISSUE THREAD

**Issue by ozgurgunes** [romannurik/Sketch-FlowExporter#6]
Open new file from Prototype Tutorial template. Export directly. You'll see almost all shape layers turn into combined shapes.

**Comment by romannurik** [comment]
Not sure I follow, could you point to a specific example in that tutorial?

**Comment by ozgurgunes** [comment]
Just export Prototyping Tutorial and check Watch Now button in Detail View artboard in Sketch file.

**Comment by romannurik** [comment]
I'm still not sure I follow what the problem is… are you saying there's a visual difference between what's exported vs. what's in Sketch?

![image](https://user-images.githubusercontent.com/100155/37436899-ae5a68f8-27c0-11e8-9faa-844c04aa3dbf.png)

**Comment by ozgurgunes** [comment]
OK. It's not happening now. I didn't understand.

**Comment by romannurik** [comment]
No problem!
