### ISSUE TITLE
Plugin only exports png

### ISSUE THREAD

**Issue by Maikenvv** [romannurik/Sketch-FlowExporter#7]
I love the idea of this plugin. Unfortunately, I can't get it to work. 

System: MacOS 10.13.3
Version: Sketch 49.1

**Steps to replicate**
1. Add the prototyping links.
![Added link](https://user-images.githubusercontent.com/5713166/37966314-665d2614-31c8-11e8-8349-27599444128c.png)

2. Test prototype in Sketch to make sure the flow works. (optional)
3. Set a page as a starting point.
![Starting page](https://user-images.githubusercontent.com/5713166/37966330-70b3a96c-31c8-11e8-9802-583a567c9a6f.png)

4. Plugins > Flow Exporter > Export prototype to HTML
5. Confirm folder for export

**Result**
Folder with pngs.

_Example_
![Export Folder](https://user-images.githubusercontent.com/5713166/37966237-25b32668-31c8-11e8-9c8e-29d045e79dad.png)

**Expected result**
A HTML file that I can open in a browser.

**Comment by romannurik** [comment]
Weird! I suspect the plugin is hitting an error before it gets to the HTML export step. Is there any way you can open the Console app on Mac and do a search for Sketch... then run the export and see if the Console app shows any errors?

**Comment by Maikenvv** [comment]
These errors were related to the plugin.

[Uploading console.txt…]()

**Comment by romannurik** [comment]
Thanks! Will look into it.

**Comment by romannurik** [comment]
Hey there, looks like the plugin is breaking on something in your file... could you either share your .sketch file or describe the prototype flows in detail?

**Comment by Maikenvv** [comment]
I can't share the file, because of a non-disclosure. The flow is actually quite simple:

       2 - 3 - 4 
    /                  \
1                       5
    \                  /
       2 - 3 - 4 

1 links to 2 pages and both 4 pages link to 5.

**Comment by romannurik** [comment]
Hey there, I just tried with this Sketch file:

![image](https://user-images.githubusercontent.com/100155/38122802-5fb5b18a-33a5-11e8-8e37-13163172d271.png)
[test.sketch.zip](https://github.com/romannurik/Sketch-FlowExporter/files/1862556/test.sketch.zip)

and it seems to export fine... any chance you could remove any identifying information from your Sketch file, or try to create a simple version that fails for you, and share again?

**Comment by acardozzo** [comment]
I'm getting the same issue. I did several tests in one situation I found the artboard responsible for the error but not the reason, but actually, I can't find where the problem it is.  See attached the log

[Plugin Output.log](https://github.com/romannurik/Sketch-FlowExporter/files/1865650/Plugin.Output.log)

**Comment by romannurik** [comment]
Are any of the artboards symbols?

**Comment by acardozzo** [comment]
None artboard is entirely a symbol, but I have header and footer in symbol w/ hotspot. But I've removed those to test and it fails anyway. I did another test creating a simple file with a header in symbol and the plugin exports fine.

**Comment by romannurik** [comment]
Hm OK. That log shows the same exact error as the other comment, so looks like a single consistent issue. I think if someone could share a Sketch file (publicly or privately) it'd help most.

**Comment by acardozzo** [comment]
I can share privately. Does it works for you?

**Comment by romannurik** [comment]
That would be great thanks! Just email roman AT nurik DOT net

**Comment by acardozzo** [comment]
Done!

**Comment by romannurik** [comment]
@acardozzo haven't received it yet :-/

**Comment by acardozzo** [comment]
I sent yesterday earlier. I didn't get any error message from your server. Is there another way to send it?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by acardozzo** [comment]
I sent again. But now to correct email :)

**Comment by romannurik** [comment]
Thanks! I did some digging and it looks like a weird issue in Sketch (I think?) where a hotspot/layer can be linked to an artboard that no longer exists. I'll just need to handle that case. A fix should be relatively straightforward, stay tuned!

**Comment by acardozzo** [comment]
👍 Thank you for the feedback!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
