### ISSUE TITLE
how to export 2x img

### ISSUE THREAD

**Issue by ZTfer** [romannurik/Sketch-FlowExporter#8]
how to export 2x img

**Comment by romannurik** [comment]
the plugin currently only exports in 1x. exporting in 2x could be a nice option. see also #3 for additional possible options

**Comment by romannurik** [comment]
This is now available... if you run `Set Prototype Export Options` you can choose 1x or 2x, and set the default to 2x.

**Comment by ZTfer** [comment]
Wow, that's awesome，Thank you very much
