### ISSUE TITLE
[macOS El Capitan] Plugin doesn't work on macOS 10.11 El Capitan

### ISSUE THREAD

**Issue by caninjpn** [romannurik/Sketch-FlowExporter#9]
I downloaded the latest version and installed the plugin, linked the paths, and set the default screen. but when I click on "export prototype to html", nothing happens. ,No error, no output.

**Comment by romannurik** [comment]
Hey there, could you share a bit more detail about which version of Sketch, macOS, and the plugin you're using? It'd also be helpful to see errors that might pop up in the "Console" app on your Mac when running the command. You can do a search for "sketch" to keep the noise down in that app.

**Comment by caninjpn** [comment]
Sketch Ver. 49.2
MacOS: OSX El Capitan ver.10.11.16
Plugin: Flow Exporter 0.1.5
I  opened up Console to find the following:
Console Message
![error](https://user-images.githubusercontent.com/33068896/38228399-1d66d696-373e-11e8-8457-e69181dd6f0c.png)

Note: I've downloaded the zip if that helps.

**Comment by romannurik** [comment]
Ah I haven't tested on El Capitan .. could be something to do with that. For now if there are any additional logs you can see around the one you screenshotted that would help too. Thank you for your help!

**Comment by caninjpn** [comment]
I've tried multiple times, and all returns the above Exception for anything related to FlowExporter.

**Comment by jayliu50** [comment]
The plugin won't even build in El Capitan. The error I'm getting is 

```
2018-06-02 18:22:48.834 ibtoold[45897:5390848] Exception raised while unarchiving document objects - IBDocumentMissingCapabilityException
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.ibtool.errors</key>
	<array>
		<dict>
			<key>description</key>
			<string>The document “(null)” requires Xcode 8.0 or later.</string>
			<key>recovery-suggestion</key>
			<string>This version does not support documents saved in the Xcode 8 format. Open this document with Xcode 8.0 or later.</string>
		</dict>
	</array>
</dict>
</plist>
```

The command being run is `ibtool --compile assets/Prefs.nib src/Prefs.xib`.

Thus, I don't see El Capitan being supported unless code is refactored so that it does not use NIB.

**Comment by romannurik** [comment]
I'm going to close this out as El Capitan is very old.
